require('plugins')
require('basic')
require('maps')
require('bootstrap')
require('colorscheme')
require('plugin-config.telescope')
require('plugin-config.toggleterm')
require('plugin-config.lualine')
require('plugin-config.transparent')
require('plugin-config.gitsigns')
require('plugin-config.coc')
require('plugin-config.move')
require('plugin-config.fzf')
require('plugin-config.nvimtree')
require('plugin-config.neovim-session-manager')

