require('basic')
require('maps')
require('bootstrap')
require('plugins')
require('colorscheme')
require('plugin-config.telescope')
require('plugin-config.toggleterm')
require('plugin-config.lualine')
require('plugin-config.transparent')
require('plugin-config.gitsigns')
require('plugin-config.coc')
-- require('plugin-config.treesitter')
